blog/urls.py
from django.urls import path

from . import views
app_name = 'blog'
urlpatterns = [
     path('', views.home_page, name='home_page'),
]

my_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models

# Create your models here.

views.py
from django.shortcuts import render

def home_page(request):

    if request.method == 'POST':
        comment = request.POST.get('comment')
        user = request.POST.get("username")

        print(comment * 10)
        return render(request, 'blog/home_page.html', {'comment': comment, 'username': user})

    return render(request, 'blog/home_page.html')

# Create your views here.

blog/templates/blog/home_page.html
<form action="{% url 'blog:home_page' %}" method="POST">

<!DOCTYPE html>
<html>
<head>
 <title>Welcome to Roger's Awesome Blog</title>
</head>
<body>
 <!-- Site Header -->
 <h1>Hi. I am Roger. Welcome to my blog!</h1>

<!-- Blog Post -->
 <h2>My First Blog Post</h2>
 <p>Here is my first blog post. Learning computer swcience is really important nowadays. computer science can help people with various kinds of work.
 </p>
 <p><img src="http://www.cdjxihs.com/upfile/Upload/20171123/20171123233265765.jpg"></p>

 <p>I have a really good computer science teacher called Kalu. I encourage all of you to study computer science with him.</p>
<p>He majored in psychology at Texas Tech University. He also received a doctor degree of law study and a high technology certificate at Santa Clara University. He became a registered lawyer, a psychology teacher and a software engineer in California, the United States. He was good at using professional knowledge to guide the students. He worked in a well-known software company in the United States, China and Japan, and served as a teacher of English and computer science in well-known universities and high schools in China. He also has rich experience in practical computer teaching.</p>
<p>I suggest all of you to study with him.</p>
<!-- Like And Comment -->
 <button>Like</button>
 <h2>Leave a Comment</h2>
 <form action="{% url 'blog:home_page' %}" method="POST">
 {% csrf_token %}
 <input type="text" placeholder="Please Enter Your username" name="username"><br><br>
 <textarea name="comment" placeholder="Please Enter Your Comment"></textarea><br>
 <input type="submit" value="Post Me!">
 </form>

<h2>Comments</h2>
 User {{username}} says: {{comment}}
</body>
</html>

</from>